### ISSUE TITLE
String with bracket issue 

### ISSUE THREAD

**Issue by bhargav-kahar-everestek** [nbubna/Case#32]
Hi,

Strange behavior when **(No)** is there in string.
E.G.
```
title("ABC (No)") // ABC (No) 
title("ABC (NO)") // Abc (No)  
title("ABC (NT)") // Abc (Nt)
title("ABC (XX)") // Abc (Xx)
```

Same with **capital**, I haven't checked other.
Hope to resolve soon.

**Comment by nbubna** [comment]
It has nothing to do with the parentheses (what you called brackets). Same happens without them. More importantly, these things happen:

Case.of("ABC No") -> capital
Case.of("ABC NO") -> upper

And i'm honestly not convinced it should do any different. Acronyms are the biggest headache for case changing. Both title and capital case make an earnest effort to respect acronyms when they are included in input, since acronyms are "legal" in those cases. By passing in a string that has an upper-case "ABC" and a capital-case "No", there is little choice but to assume the ABC was intended to be an acronym and leave it as-is.

You can force the issue by first converting to a case that doesn't support acronyms:

Case.title(Case.upper("ABC (No)"));
